project:
  type: website
  output-dir: docs/
  render: 
    - index.qmd
website:
  title: "Load These Images"
  page-footer:
    background: light
    left: University of Maryland, Baltimore
    right: Built with [Quarto](https://quarto.org/).